import type { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-postgres'
import { sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_paginas_blocks_texto_pagina_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_texto_pagina_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_texto_pagina_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_imagen_pagina_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_imagen_pagina_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_imagen_pagina_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_boton_pagina_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_boton_pagina_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_boton_pagina_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_codigo_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_codigo_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_codigo_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_toggle_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_toggle_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_toggle_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_video_pagina_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_video_pagina_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_video_pagina_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_blurb_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_blurb_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_blurb_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_slider_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_slider_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_slider_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_mapa_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_mapa_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_mapa_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_icono_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_icono_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_blocks_icono_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_bloques_filas_pt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_bloques_filas_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_bloques_filas_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_bloques_filas_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_bloques_pt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_paginas_bloques_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_texto_kb_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_texto_kb_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_texto_kb_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_imagen_kb_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_imagen_kb_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_imagen_kb_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_boton_kb_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_boton_kb_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_boton_kb_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_blurb_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_blurb_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_blurb_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_gallery_ritmo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_gallery_ritmo_mb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_blocks_gallery_ritmo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_cuerpo_pt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_cuerpo_pb_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_cuerpo_mt_unidad767" AS ENUM('px', 'pct');
  CREATE TYPE "public"."enum_articulos_kb_cuerpo_mb_unidad767" AS ENUM('px', 'pct');
  ALTER TABLE "paginas_blocks_texto_pagina" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "paginas_blocks_texto_pagina" ADD COLUMN "ritmo_mt_unidad767" "enum_paginas_blocks_texto_pagina_ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_texto_pagina" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "paginas_blocks_texto_pagina" ADD COLUMN "ritmo_mb_unidad767" "enum_paginas_blocks_texto_pagina_ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_texto_pagina" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "paginas_blocks_texto_pagina" ADD COLUMN "ritmo_pb_unidad767" "enum_paginas_blocks_texto_pagina_ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_imagen_pagina" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "paginas_blocks_imagen_pagina" ADD COLUMN "ritmo_mt_unidad767" "enum_paginas_blocks_imagen_pagina_ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_imagen_pagina" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "paginas_blocks_imagen_pagina" ADD COLUMN "ritmo_mb_unidad767" "enum_paginas_blocks_imagen_pagina_ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_imagen_pagina" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "paginas_blocks_imagen_pagina" ADD COLUMN "ritmo_pb_unidad767" "enum_paginas_blocks_imagen_pagina_ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_boton_pagina" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "paginas_blocks_boton_pagina" ADD COLUMN "ritmo_mt_unidad767" "enum_paginas_blocks_boton_pagina_ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_boton_pagina" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "paginas_blocks_boton_pagina" ADD COLUMN "ritmo_mb_unidad767" "enum_paginas_blocks_boton_pagina_ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_boton_pagina" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "paginas_blocks_boton_pagina" ADD COLUMN "ritmo_pb_unidad767" "enum_paginas_blocks_boton_pagina_ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_codigo" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "paginas_blocks_codigo" ADD COLUMN "ritmo_mt_unidad767" "enum_paginas_blocks_codigo_ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_codigo" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "paginas_blocks_codigo" ADD COLUMN "ritmo_mb_unidad767" "enum_paginas_blocks_codigo_ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_codigo" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "paginas_blocks_codigo" ADD COLUMN "ritmo_pb_unidad767" "enum_paginas_blocks_codigo_ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_toggle" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "paginas_blocks_toggle" ADD COLUMN "ritmo_mt_unidad767" "enum_paginas_blocks_toggle_ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_toggle" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "paginas_blocks_toggle" ADD COLUMN "ritmo_mb_unidad767" "enum_paginas_blocks_toggle_ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_toggle" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "paginas_blocks_toggle" ADD COLUMN "ritmo_pb_unidad767" "enum_paginas_blocks_toggle_ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_video_pagina" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "paginas_blocks_video_pagina" ADD COLUMN "ritmo_mt_unidad767" "enum_paginas_blocks_video_pagina_ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_video_pagina" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "paginas_blocks_video_pagina" ADD COLUMN "ritmo_mb_unidad767" "enum_paginas_blocks_video_pagina_ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_video_pagina" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "paginas_blocks_video_pagina" ADD COLUMN "ritmo_pb_unidad767" "enum_paginas_blocks_video_pagina_ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_blurb" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "paginas_blocks_blurb" ADD COLUMN "ritmo_mt_unidad767" "enum_paginas_blocks_blurb_ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_blurb" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "paginas_blocks_blurb" ADD COLUMN "ritmo_mb_unidad767" "enum_paginas_blocks_blurb_ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_blurb" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "paginas_blocks_blurb" ADD COLUMN "ritmo_pb_unidad767" "enum_paginas_blocks_blurb_ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_slider" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "paginas_blocks_slider" ADD COLUMN "ritmo_mt_unidad767" "enum_paginas_blocks_slider_ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_slider" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "paginas_blocks_slider" ADD COLUMN "ritmo_mb_unidad767" "enum_paginas_blocks_slider_ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_slider" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "paginas_blocks_slider" ADD COLUMN "ritmo_pb_unidad767" "enum_paginas_blocks_slider_ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_mapa" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "paginas_blocks_mapa" ADD COLUMN "ritmo_mt_unidad767" "enum_paginas_blocks_mapa_ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_mapa" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "paginas_blocks_mapa" ADD COLUMN "ritmo_mb_unidad767" "enum_paginas_blocks_mapa_ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_mapa" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "paginas_blocks_mapa" ADD COLUMN "ritmo_pb_unidad767" "enum_paginas_blocks_mapa_ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_icono" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "paginas_blocks_icono" ADD COLUMN "ritmo_mt_unidad767" "enum_paginas_blocks_icono_ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_icono" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "paginas_blocks_icono" ADD COLUMN "ritmo_mb_unidad767" "enum_paginas_blocks_icono_ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_icono" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "paginas_blocks_icono" ADD COLUMN "ritmo_pb_unidad767" "enum_paginas_blocks_icono_ritmo_pb_unidad767";
  ALTER TABLE "paginas_bloques_filas" ADD COLUMN "pt_valor767" numeric;
  ALTER TABLE "paginas_bloques_filas" ADD COLUMN "pt_unidad767" "enum_paginas_bloques_filas_pt_unidad767";
  ALTER TABLE "paginas_bloques_filas" ADD COLUMN "pb_valor767" numeric;
  ALTER TABLE "paginas_bloques_filas" ADD COLUMN "pb_unidad767" "enum_paginas_bloques_filas_pb_unidad767";
  ALTER TABLE "paginas_bloques_filas" ADD COLUMN "mt_valor767" numeric;
  ALTER TABLE "paginas_bloques_filas" ADD COLUMN "mt_unidad767" "enum_paginas_bloques_filas_mt_unidad767";
  ALTER TABLE "paginas_bloques_filas" ADD COLUMN "mb_valor767" numeric;
  ALTER TABLE "paginas_bloques_filas" ADD COLUMN "mb_unidad767" "enum_paginas_bloques_filas_mb_unidad767";
  ALTER TABLE "paginas_bloques" ADD COLUMN "pt_valor767" numeric;
  ALTER TABLE "paginas_bloques" ADD COLUMN "pt_unidad767" "enum_paginas_bloques_pt_unidad767";
  ALTER TABLE "paginas_bloques" ADD COLUMN "pb_valor767" numeric;
  ALTER TABLE "paginas_bloques" ADD COLUMN "pb_unidad767" "enum_paginas_bloques_pb_unidad767";
  ALTER TABLE "articulos_kb_blocks_texto_kb" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_texto_kb" ADD COLUMN "ritmo_mt_unidad767" "enum_articulos_kb_blocks_texto_kb_ritmo_mt_unidad767";
  ALTER TABLE "articulos_kb_blocks_texto_kb" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_texto_kb" ADD COLUMN "ritmo_mb_unidad767" "enum_articulos_kb_blocks_texto_kb_ritmo_mb_unidad767";
  ALTER TABLE "articulos_kb_blocks_texto_kb" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_texto_kb" ADD COLUMN "ritmo_pb_unidad767" "enum_articulos_kb_blocks_texto_kb_ritmo_pb_unidad767";
  ALTER TABLE "articulos_kb_blocks_imagen_kb" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_imagen_kb" ADD COLUMN "ritmo_mt_unidad767" "enum_articulos_kb_blocks_imagen_kb_ritmo_mt_unidad767";
  ALTER TABLE "articulos_kb_blocks_imagen_kb" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_imagen_kb" ADD COLUMN "ritmo_mb_unidad767" "enum_articulos_kb_blocks_imagen_kb_ritmo_mb_unidad767";
  ALTER TABLE "articulos_kb_blocks_imagen_kb" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_imagen_kb" ADD COLUMN "ritmo_pb_unidad767" "enum_articulos_kb_blocks_imagen_kb_ritmo_pb_unidad767";
  ALTER TABLE "articulos_kb_blocks_boton_kb" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_boton_kb" ADD COLUMN "ritmo_mt_unidad767" "enum_articulos_kb_blocks_boton_kb_ritmo_mt_unidad767";
  ALTER TABLE "articulos_kb_blocks_boton_kb" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_boton_kb" ADD COLUMN "ritmo_mb_unidad767" "enum_articulos_kb_blocks_boton_kb_ritmo_mb_unidad767";
  ALTER TABLE "articulos_kb_blocks_boton_kb" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_boton_kb" ADD COLUMN "ritmo_pb_unidad767" "enum_articulos_kb_blocks_boton_kb_ritmo_pb_unidad767";
  ALTER TABLE "articulos_kb_blocks_blurb" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_blurb" ADD COLUMN "ritmo_mt_unidad767" "enum_articulos_kb_blocks_blurb_ritmo_mt_unidad767";
  ALTER TABLE "articulos_kb_blocks_blurb" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_blurb" ADD COLUMN "ritmo_mb_unidad767" "enum_articulos_kb_blocks_blurb_ritmo_mb_unidad767";
  ALTER TABLE "articulos_kb_blocks_blurb" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_blurb" ADD COLUMN "ritmo_pb_unidad767" "enum_articulos_kb_blocks_blurb_ritmo_pb_unidad767";
  ALTER TABLE "articulos_kb_blocks_gallery" ADD COLUMN "ritmo_mt_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_gallery" ADD COLUMN "ritmo_mt_unidad767" "enum_articulos_kb_blocks_gallery_ritmo_mt_unidad767";
  ALTER TABLE "articulos_kb_blocks_gallery" ADD COLUMN "ritmo_mb_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_gallery" ADD COLUMN "ritmo_mb_unidad767" "enum_articulos_kb_blocks_gallery_ritmo_mb_unidad767";
  ALTER TABLE "articulos_kb_blocks_gallery" ADD COLUMN "ritmo_pb_valor767" numeric;
  ALTER TABLE "articulos_kb_blocks_gallery" ADD COLUMN "ritmo_pb_unidad767" "enum_articulos_kb_blocks_gallery_ritmo_pb_unidad767";
  ALTER TABLE "articulos_kb_cuerpo" ADD COLUMN "pt_valor767" numeric;
  ALTER TABLE "articulos_kb_cuerpo" ADD COLUMN "pt_unidad767" "enum_articulos_kb_cuerpo_pt_unidad767";
  ALTER TABLE "articulos_kb_cuerpo" ADD COLUMN "pb_valor767" numeric;
  ALTER TABLE "articulos_kb_cuerpo" ADD COLUMN "pb_unidad767" "enum_articulos_kb_cuerpo_pb_unidad767";
  ALTER TABLE "articulos_kb_cuerpo" ADD COLUMN "mt_valor767" numeric;
  ALTER TABLE "articulos_kb_cuerpo" ADD COLUMN "mt_unidad767" "enum_articulos_kb_cuerpo_mt_unidad767";
  ALTER TABLE "articulos_kb_cuerpo" ADD COLUMN "mb_valor767" numeric;
  ALTER TABLE "articulos_kb_cuerpo" ADD COLUMN "mb_unidad767" "enum_articulos_kb_cuerpo_mb_unidad767";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "paginas_blocks_texto_pagina" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "paginas_blocks_texto_pagina" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_texto_pagina" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "paginas_blocks_texto_pagina" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_texto_pagina" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "paginas_blocks_texto_pagina" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_imagen_pagina" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "paginas_blocks_imagen_pagina" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_imagen_pagina" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "paginas_blocks_imagen_pagina" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_imagen_pagina" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "paginas_blocks_imagen_pagina" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_boton_pagina" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "paginas_blocks_boton_pagina" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_boton_pagina" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "paginas_blocks_boton_pagina" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_boton_pagina" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "paginas_blocks_boton_pagina" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_codigo" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "paginas_blocks_codigo" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_codigo" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "paginas_blocks_codigo" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_codigo" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "paginas_blocks_codigo" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_toggle" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "paginas_blocks_toggle" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_toggle" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "paginas_blocks_toggle" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_toggle" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "paginas_blocks_toggle" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_video_pagina" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "paginas_blocks_video_pagina" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_video_pagina" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "paginas_blocks_video_pagina" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_video_pagina" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "paginas_blocks_video_pagina" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_blurb" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "paginas_blocks_blurb" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_blurb" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "paginas_blocks_blurb" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_blurb" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "paginas_blocks_blurb" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_slider" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "paginas_blocks_slider" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_slider" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "paginas_blocks_slider" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_slider" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "paginas_blocks_slider" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_mapa" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "paginas_blocks_mapa" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_mapa" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "paginas_blocks_mapa" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_mapa" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "paginas_blocks_mapa" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "paginas_blocks_icono" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "paginas_blocks_icono" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "paginas_blocks_icono" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "paginas_blocks_icono" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "paginas_blocks_icono" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "paginas_blocks_icono" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "paginas_bloques_filas" DROP COLUMN "pt_valor767";
  ALTER TABLE "paginas_bloques_filas" DROP COLUMN "pt_unidad767";
  ALTER TABLE "paginas_bloques_filas" DROP COLUMN "pb_valor767";
  ALTER TABLE "paginas_bloques_filas" DROP COLUMN "pb_unidad767";
  ALTER TABLE "paginas_bloques_filas" DROP COLUMN "mt_valor767";
  ALTER TABLE "paginas_bloques_filas" DROP COLUMN "mt_unidad767";
  ALTER TABLE "paginas_bloques_filas" DROP COLUMN "mb_valor767";
  ALTER TABLE "paginas_bloques_filas" DROP COLUMN "mb_unidad767";
  ALTER TABLE "paginas_bloques" DROP COLUMN "pt_valor767";
  ALTER TABLE "paginas_bloques" DROP COLUMN "pt_unidad767";
  ALTER TABLE "paginas_bloques" DROP COLUMN "pb_valor767";
  ALTER TABLE "paginas_bloques" DROP COLUMN "pb_unidad767";
  ALTER TABLE "articulos_kb_blocks_texto_kb" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "articulos_kb_blocks_texto_kb" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "articulos_kb_blocks_texto_kb" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "articulos_kb_blocks_texto_kb" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "articulos_kb_blocks_texto_kb" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "articulos_kb_blocks_texto_kb" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "articulos_kb_blocks_imagen_kb" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "articulos_kb_blocks_imagen_kb" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "articulos_kb_blocks_imagen_kb" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "articulos_kb_blocks_imagen_kb" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "articulos_kb_blocks_imagen_kb" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "articulos_kb_blocks_imagen_kb" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "articulos_kb_blocks_boton_kb" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "articulos_kb_blocks_boton_kb" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "articulos_kb_blocks_boton_kb" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "articulos_kb_blocks_boton_kb" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "articulos_kb_blocks_boton_kb" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "articulos_kb_blocks_boton_kb" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "articulos_kb_blocks_blurb" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "articulos_kb_blocks_blurb" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "articulos_kb_blocks_blurb" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "articulos_kb_blocks_blurb" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "articulos_kb_blocks_blurb" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "articulos_kb_blocks_blurb" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "articulos_kb_blocks_gallery" DROP COLUMN "ritmo_mt_valor767";
  ALTER TABLE "articulos_kb_blocks_gallery" DROP COLUMN "ritmo_mt_unidad767";
  ALTER TABLE "articulos_kb_blocks_gallery" DROP COLUMN "ritmo_mb_valor767";
  ALTER TABLE "articulos_kb_blocks_gallery" DROP COLUMN "ritmo_mb_unidad767";
  ALTER TABLE "articulos_kb_blocks_gallery" DROP COLUMN "ritmo_pb_valor767";
  ALTER TABLE "articulos_kb_blocks_gallery" DROP COLUMN "ritmo_pb_unidad767";
  ALTER TABLE "articulos_kb_cuerpo" DROP COLUMN "pt_valor767";
  ALTER TABLE "articulos_kb_cuerpo" DROP COLUMN "pt_unidad767";
  ALTER TABLE "articulos_kb_cuerpo" DROP COLUMN "pb_valor767";
  ALTER TABLE "articulos_kb_cuerpo" DROP COLUMN "pb_unidad767";
  ALTER TABLE "articulos_kb_cuerpo" DROP COLUMN "mt_valor767";
  ALTER TABLE "articulos_kb_cuerpo" DROP COLUMN "mt_unidad767";
  ALTER TABLE "articulos_kb_cuerpo" DROP COLUMN "mb_valor767";
  ALTER TABLE "articulos_kb_cuerpo" DROP COLUMN "mb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_texto_pagina_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_texto_pagina_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_texto_pagina_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_imagen_pagina_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_imagen_pagina_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_imagen_pagina_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_boton_pagina_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_boton_pagina_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_boton_pagina_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_codigo_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_codigo_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_codigo_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_toggle_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_toggle_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_toggle_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_video_pagina_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_video_pagina_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_video_pagina_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_blurb_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_blurb_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_blurb_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_slider_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_slider_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_slider_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_mapa_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_mapa_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_mapa_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_icono_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_icono_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_paginas_blocks_icono_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_paginas_bloques_filas_pt_unidad767";
  DROP TYPE "public"."enum_paginas_bloques_filas_pb_unidad767";
  DROP TYPE "public"."enum_paginas_bloques_filas_mt_unidad767";
  DROP TYPE "public"."enum_paginas_bloques_filas_mb_unidad767";
  DROP TYPE "public"."enum_paginas_bloques_pt_unidad767";
  DROP TYPE "public"."enum_paginas_bloques_pb_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_texto_kb_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_texto_kb_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_texto_kb_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_imagen_kb_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_imagen_kb_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_imagen_kb_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_boton_kb_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_boton_kb_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_boton_kb_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_blurb_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_blurb_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_blurb_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_gallery_ritmo_mt_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_gallery_ritmo_mb_unidad767";
  DROP TYPE "public"."enum_articulos_kb_blocks_gallery_ritmo_pb_unidad767";
  DROP TYPE "public"."enum_articulos_kb_cuerpo_pt_unidad767";
  DROP TYPE "public"."enum_articulos_kb_cuerpo_pb_unidad767";
  DROP TYPE "public"."enum_articulos_kb_cuerpo_mt_unidad767";
  DROP TYPE "public"."enum_articulos_kb_cuerpo_mb_unidad767";`)
}
