/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    sectores: Sectore;
    monograficos: Monografico;
    productos: Producto;
    casos: Caso;
    faqs: Faq;
    'taxonomia-sectores': TaxonomiaSectore;
    'entradas-blog': EntradasBlog;
    'terminos-kunakpedia': TerminosKunakpedia;
    'documentos-cientificos': DocumentosCientifico;
    'articulos-kb': ArticulosKb;
    categorias: Categoria;
    etiquetas: Etiqueta;
    'categorias-recursos': CategoriasRecurso;
    'categorias-cientificas': CategoriasCientifica;
    media: Media;
    slugs: Slug;
    usuarios: Usuario;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    sectores: SectoresSelect<false> | SectoresSelect<true>;
    monograficos: MonograficosSelect<false> | MonograficosSelect<true>;
    productos: ProductosSelect<false> | ProductosSelect<true>;
    casos: CasosSelect<false> | CasosSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'taxonomia-sectores': TaxonomiaSectoresSelect<false> | TaxonomiaSectoresSelect<true>;
    'entradas-blog': EntradasBlogSelect<false> | EntradasBlogSelect<true>;
    'terminos-kunakpedia': TerminosKunakpediaSelect<false> | TerminosKunakpediaSelect<true>;
    'documentos-cientificos': DocumentosCientificosSelect<false> | DocumentosCientificosSelect<true>;
    'articulos-kb': ArticulosKbSelect<false> | ArticulosKbSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    etiquetas: EtiquetasSelect<false> | EtiquetasSelect<true>;
    'categorias-recursos': CategoriasRecursosSelect<false> | CategoriasRecursosSelect<true>;
    'categorias-cientificas': CategoriasCientificasSelect<false> | CategoriasCientificasSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    slugs: SlugsSelect<false> | SlugsSelect<true>;
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectores".
 */
export interface Sectore {
  id: number;
  slug: string;
  seo: {
    title: string;
    description?: string | null;
    ogImage?: string | null;
    canonical?: string | null;
  };
  breadcrumb?:
    | {
        label: string;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  header: {
    kicker: string;
    title: string;
    image: number | Media;
  };
  hero: {
    image: {
      src: number | Media;
      alt?: string | null;
    };
    ctas?:
      | {
          label: string;
          href: string;
          external?: boolean | null;
          id?: string | null;
        }[]
      | null;
    heading: string;
    /**
     * Defecto "#0075c9" — §1.4
     */
    headingColor?: string | null;
    paragraphs?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
  };
  body?:
    | (
        | {
            title: string;
            body?:
              | {
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            cta: {
              label: string;
              href: string;
              external?: boolean | null;
            };
            image?: (number | null) | Media;
            /**
             * Defecto "foto" — §1.4 · CLAUDE.md §Estructura que en realidad es contenido
             */
            variante?: ('foto' | 'fondo') | null;
            /**
             * Defecto "seccion" — §1.4 · medido en los 8 sectores vivos (tree-todos)
             */
            flujo?: ('seccion' | 'seccionRasa' | 'fila' | 'filaPegada') | null;
            /**
             * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
             */
            anchoPct?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaDescarga';
          }
        | {
            left: {
              title: string;
              items?:
                | {
                    texto: string;
                    id?: string | null;
                  }[]
                | null;
            };
            right: {
              title: string;
              items?:
                | {
                    texto: string;
                    id?: string | null;
                  }[]
                | null;
            };
            /**
             * Defecto "seccion" — §1.4 · medido en los 8 sectores vivos (tree-todos)
             */
            flujo?: ('seccion' | 'seccionRasa' | 'fila' | 'filaPegada') | null;
            /**
             * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
             */
            anchoPct?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'beneficiosAplicaciones';
          }
        | {
            claim: string;
            image: {
              src: number | Media;
              alt?: string | null;
            };
            /**
             * Defecto "seccion" — §1.4 · medido en los 8 sectores vivos (tree-todos)
             */
            flujo?: ('seccion' | 'seccionRasa' | 'fila' | 'filaPegada') | null;
            /**
             * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
             */
            anchoPct?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'claimConFoto';
          }
        | {
            intro?: string | null;
            left?:
              | {
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            right?:
              | {
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Defecto "seccion" — §1.4 · medido en los 8 sectores vivos (tree-todos)
             */
            flujo?: ('seccion' | 'seccionRasa' | 'fila' | 'filaPegada') | null;
            /**
             * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
             */
            anchoPct?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'listaSimple2Col';
          }
        | {
            title: string;
            intro?: string | null;
            pins?:
              | {
                  title: string;
                  lat: number;
                  lng: number;
                  id?: string | null;
                }[]
              | null;
            /**
             * Defecto "seccion" — §1.4 · medido en los 8 sectores vivos (tree-todos)
             */
            flujo?: ('seccion' | 'seccionRasa' | 'fila' | 'filaPegada') | null;
            /**
             * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
             */
            anchoPct?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mapaProyectos';
          }
      )[]
    | null;
  ctaSlides?:
    | {
        heading: string;
        cta: {
          label: string;
          href: string;
          external?: boolean | null;
        };
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  soluciones?: (number | Producto)[] | null;
  proyectos: {
    title: string;
    cta: {
      label: string;
      href: string;
      external?: boolean | null;
    };
    /**
     * Teaser VERBATIM, no proyección: no se actualiza solo si cambia el caso (§F2-2 · TEASER).
     */
    posts?:
      | {
          client: string;
          sector: string;
          sectorHref?: string | null;
          title: string;
          image: number | Media;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  articulos: {
    title: string;
    cta: {
      label: string;
      href: string;
      external?: boolean | null;
    };
    /**
     * Teaser VERBATIM, no proyección: no se actualiza solo si cambia la entrada (§F2-2 · TEASER).
     */
    posts?:
      | {
          title: string;
          /**
           * Fecha VERBATIM en la forma del teaser ("Mar 25, 2026"). El documento la escribe de otra forma ("25 marzo 2026") y las dos son verbatim: no se derivan la una de la otra.
           */
          date: string;
          image: number | Media;
          href: string;
          excerpt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  taxonomy: {
    label: string;
    href: string;
    external?: boolean | null;
  };
  footerStripImage?: (number | null) | Media;
  /**
   * Sólo «Publicado» sale en el sitio. Un borrador se ve en la preview con credencial.
   */
  estado: 'borrador' | 'publicado';
  /**
   * Si está en Borrador y esta hora pasa, el cron lo publica y reconstruye. Vacío = manual.
   */
  publicarEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  /**
   * Procedencia: la ruta con la que la migración subió este fichero (/images/…). Vacío en las altas hechas desde el admin, que no tienen origen — y entonces el render usa /api/media/file/<filename>, la única URL que puede funcionar para ellas.
   */
  rutaOrigen?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    w300?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w768?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cardWide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productos".
 */
export interface Producto {
  id: number;
  slug: string;
  titulo: string;
  /**
   * Defecto "ficha" — §2e · 23 de 24 · productos/DECISION.md
   */
  tipo?: ('ficha' | 'catalogo') | null;
  /**
   * Segmento anterior al slug. Ausente = producto de primer nivel (6 de 24). PR-SP2: `cartuchos-inteligentes` es categoría (17) y `sensor-de-calidad-del-aire` es OTRO producto (1) — por eso hoy es select y no relación.
   */
  padre?: ('cartuchos-inteligentes' | 'sensor-de-calidad-del-aire') | null;
  seo: {
    title: string;
    description?: string | null;
    ogImage?: string | null;
  };
  tagline?: string | null;
  description?: string | null;
  highlight?: string | null;
  /**
   * Defecto "Ventajas" — §2b.1 (4) · C-SP14
   */
  bulletsTitulo?: string | null;
  bullets?:
    | {
        /**
         * HTML de LÍNEA (`CampoRicoEnLinea`): strong · b · i · br · sub · sup · a. Sin bloques ni `<p>` propio.
         */
        texto: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  cuerpo?:
    | (
        | {
            texto: string;
            /**
             * Defecto 3 — §1.5 · MonoNivel 2|3|4 — el titular lo lee con `?? 3` en MonoCuerpo.tsx
             */
            nivel?: number | null;
            ritmo?: {
              mt?: number | null;
              mb?: number | null;
              pt?: number | null;
              pb?: number | null;
              pr?: number | null;
              mbAlterno?: boolean | null;
            };
            /**
             * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
             */
            anchoPct?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'titular';
          }
        | {
            texto: string;
            /**
             * Defecto 2 — §1.5 · MonoNivel 2|3|4 — el claim lo lee con `?? 2` en MonoCuerpo.tsx
             */
            nivel?: number | null;
            ritmo?: {
              mt?: number | null;
              mb?: number | null;
              pt?: number | null;
              pb?: number | null;
              pr?: number | null;
              mbAlterno?: boolean | null;
            };
            /**
             * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
             */
            anchoPct?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'claim';
          }
        | {
            bloques: (
              | {
                  p: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  pb?: number | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'p';
                }
              | {
                  ul?:
                    | {
                        texto: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        };
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'ul';
                }
              | {
                  claim?: string | null;
                  /**
                   * Defecto 2 — §1.5 · MonoNivel 2|3|4 — el claim lo lee con `?? 2` en MonoCuerpo.tsx
                   */
                  nivel?: number | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'claim';
                }
              | {
                  titular: string;
                  /**
                   * Defecto 3 — §1.5 · MonoNivel 2|3|4 — el titular lo lee con `?? 3` en MonoCuerpo.tsx
                   */
                  nivel?: number | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'titular';
                }
            )[];
            /**
             * Defecto 30.6 — §1.5 · 30.6·36·45 por módulo
             */
            lh?: number | null;
            ritmo?: {
              mt?: number | null;
              mb?: number | null;
              pt?: number | null;
              pb?: number | null;
              pr?: number | null;
              mbAlterno?: boolean | null;
            };
            /**
             * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
             */
            anchoPct?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            src: number | Media;
            alt?: string | null;
            ritmo?: {
              mt?: number | null;
              mb?: number | null;
              pt?: number | null;
              pb?: number | null;
              pr?: number | null;
              mbAlterno?: boolean | null;
            };
            /**
             * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
             */
            anchoPct?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            label: string;
            href: string;
            external?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'boton';
          }
        | {
            titulo: string;
            /**
             * HTML del corpus (CMS-0e · §3.1). Admite las 43 etiquetas censadas en 209/209. Prohibido `<script>` (§3.3 · T4). Rango medido: 275–69 784 caracteres.
             */
            contenido?: string | null;
            abiertoPorDefecto?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'toggle';
          }
        | {
            titulo?: string | null;
            /**
             * HTML de LÍNEA (`CampoRicoEnLinea`): strong · b · i · br · sub · sup · a. Sin bloques ni `<p>` propio.
             */
            texto?: string | null;
            icono?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blurb';
          }
        | {
            diapositivas?:
              | {
                  heading?: string | null;
                  /**
                   * HTML de LÍNEA (`CampoRicoEnLinea`): strong · b · i · br · sub · sup · a. Sin bloques ni `<p>` propio.
                   */
                  texto?: string | null;
                  image?: (number | null) | Media;
                  cta?: {
                    label?: string | null;
                    href?: string | null;
                    external?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
        | {
            imagenes?:
              | {
                  src: number | Media;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            archivo?: (number | null) | Media;
            url?: string | null;
            poster?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            title: string;
            body?:
              | {
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            cta: {
              label: string;
              href: string;
              external?: boolean | null;
            };
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            cabeceras?:
              | {
                  texto: string;
                  id?: string | null;
                }[]
              | null;
            filas?:
              | {
                  celdas?:
                    | {
                        texto?: string | null;
                        fuerte?: string | null;
                        resto?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'table';
          }
      )[]
    | null;
  /**
   * Sólo «Publicado» sale en el sitio. Un borrador se ve en la preview con credencial.
   */
  estado: 'borrador' | 'publicado';
  /**
   * Si está en Borrador y esta hora pasa, el cron lo publica y reconstruye. Vacío = manual.
   */
  publicarEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monograficos".
 */
export interface Monografico {
  id: number;
  slug: string;
  seo: {
    title: string;
    description?: string | null;
    ogImage?: string | null;
    canonical?: string | null;
  };
  breadcrumb?:
    | {
        label: string;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  header: {
    kicker: string;
    title: string;
    image: number | Media;
  };
  hero: {
    image: {
      src: number | Media;
      alt?: string | null;
    };
    ctas?:
      | {
          label: string;
          href: string;
          external?: boolean | null;
          id?: string | null;
        }[]
      | null;
    modulos?:
      | {
          heading?: string | null;
          headingColor?: string | null;
          paragraphs?:
            | {
                texto: string;
                id?: string | null;
              }[]
            | null;
          mb?: number | null;
          id?: string | null;
        }[]
      | null;
    pb?: number | null;
  };
  cuerpo?:
    | {
        mt?: number | null;
        pt?: number | null;
        pb?: number | null;
        filas?:
          | {
              mt?: number | null;
              pt?: number | null;
              pb?: number | null;
              columnas?:
                | {
                    ancho: '1_4' | '1_3' | '2_5' | '1_2' | '3_5' | '2_3' | '3_4' | '4_4';
                    punteado?: boolean | null;
                    mbMovil?: number | null;
                    modulos: (
                      | {
                          texto: string;
                          /**
                           * Defecto 3 — §1.5 · MonoNivel 2|3|4 — el titular lo lee con `?? 3` en MonoCuerpo.tsx
                           */
                          nivel?: number | null;
                          ritmo?: {
                            mt?: number | null;
                            mb?: number | null;
                            pt?: number | null;
                            pb?: number | null;
                            pr?: number | null;
                            mbAlterno?: boolean | null;
                          };
                          /**
                           * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
                           */
                          anchoPct?: number | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'titular';
                        }
                      | {
                          texto: string;
                          /**
                           * Defecto 2 — §1.5 · MonoNivel 2|3|4 — el claim lo lee con `?? 2` en MonoCuerpo.tsx
                           */
                          nivel?: number | null;
                          ritmo?: {
                            mt?: number | null;
                            mb?: number | null;
                            pt?: number | null;
                            pb?: number | null;
                            pr?: number | null;
                            mbAlterno?: boolean | null;
                          };
                          /**
                           * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
                           */
                          anchoPct?: number | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'claim';
                        }
                      | {
                          bloques: (
                            | {
                                p: {
                                  root: {
                                    type: string;
                                    children: {
                                      type: any;
                                      version: number;
                                      [k: string]: unknown;
                                    }[];
                                    direction: ('ltr' | 'rtl') | null;
                                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                    indent: number;
                                    version: number;
                                  };
                                  [k: string]: unknown;
                                };
                                pb?: number | null;
                                id?: string | null;
                                blockName?: string | null;
                                blockType: 'p';
                              }
                            | {
                                ul?:
                                  | {
                                      texto: {
                                        root: {
                                          type: string;
                                          children: {
                                            type: any;
                                            version: number;
                                            [k: string]: unknown;
                                          }[];
                                          direction: ('ltr' | 'rtl') | null;
                                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                          indent: number;
                                          version: number;
                                        };
                                        [k: string]: unknown;
                                      };
                                      id?: string | null;
                                    }[]
                                  | null;
                                id?: string | null;
                                blockName?: string | null;
                                blockType: 'ul';
                              }
                            | {
                                claim?: string | null;
                                /**
                                 * Defecto 2 — §1.5 · MonoNivel 2|3|4 — el claim lo lee con `?? 2` en MonoCuerpo.tsx
                                 */
                                nivel?: number | null;
                                id?: string | null;
                                blockName?: string | null;
                                blockType: 'claim';
                              }
                            | {
                                titular: string;
                                /**
                                 * Defecto 3 — §1.5 · MonoNivel 2|3|4 — el titular lo lee con `?? 3` en MonoCuerpo.tsx
                                 */
                                nivel?: number | null;
                                id?: string | null;
                                blockName?: string | null;
                                blockType: 'titular';
                              }
                          )[];
                          /**
                           * Defecto 30.6 — §1.5 · 30.6·36·45 por módulo
                           */
                          lh?: number | null;
                          ritmo?: {
                            mt?: number | null;
                            mb?: number | null;
                            pt?: number | null;
                            pb?: number | null;
                            pr?: number | null;
                            mbAlterno?: boolean | null;
                          };
                          /**
                           * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
                           */
                          anchoPct?: number | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'texto';
                        }
                      | {
                          src: number | Media;
                          alt?: string | null;
                          ritmo?: {
                            mt?: number | null;
                            mb?: number | null;
                            pt?: number | null;
                            pb?: number | null;
                            pr?: number | null;
                            mbAlterno?: boolean | null;
                          };
                          /**
                           * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
                           */
                          anchoPct?: number | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'imagen';
                        }
                      | {
                          label: string;
                          href: string;
                          external?: boolean | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'boton';
                        }
                      | {
                          items?:
                            | {
                                titulo: string;
                                texto: string;
                                id?: string | null;
                              }[]
                            | null;
                          ritmo?: {
                            mt?: number | null;
                            mb?: number | null;
                            pt?: number | null;
                            pb?: number | null;
                            pr?: number | null;
                            mbAlterno?: boolean | null;
                          };
                          /**
                           * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
                           */
                          anchoPct?: number | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'serie';
                        }
                      | {
                          cabeceras?:
                            | {
                                texto: string;
                                id?: string | null;
                              }[]
                            | null;
                          filas?:
                            | {
                                celdas?:
                                  | {
                                      texto?: string | null;
                                      fuerte?: string | null;
                                      resto?: string | null;
                                      id?: string | null;
                                    }[]
                                  | null;
                                id?: string | null;
                              }[]
                            | null;
                          ritmo?: {
                            mt?: number | null;
                            mb?: number | null;
                            pt?: number | null;
                            pb?: number | null;
                            pr?: number | null;
                            mbAlterno?: boolean | null;
                          };
                          /**
                           * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
                           */
                          anchoPct?: number | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'tabla';
                        }
                      | {
                          title: string;
                          body?:
                            | {
                                texto: string;
                                id?: string | null;
                              }[]
                            | null;
                          cta: {
                            label: string;
                            href: string;
                            external?: boolean | null;
                          };
                          image?: (number | null) | Media;
                          ritmo?: {
                            mt?: number | null;
                            mb?: number | null;
                            pt?: number | null;
                            pb?: number | null;
                            pr?: number | null;
                            mbAlterno?: boolean | null;
                          };
                          /**
                           * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
                           */
                          anchoPct?: number | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'ctaDescarga';
                        }
                      | {
                          pins?:
                            | {
                                title: string;
                                lat: number;
                                lng: number;
                                id?: string | null;
                              }[]
                            | null;
                          ritmo?: {
                            mt?: number | null;
                            mb?: number | null;
                            pt?: number | null;
                            pb?: number | null;
                            pr?: number | null;
                            mbAlterno?: boolean | null;
                          };
                          /**
                           * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
                           */
                          anchoPct?: number | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'mapaProyectos';
                        }
                    )[];
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaSlides?:
    | {
        heading: string;
        cta: {
          label: string;
          href: string;
          external?: boolean | null;
        };
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  soluciones?: (number | Producto)[] | null;
  proyectos: {
    title: string;
    cta: {
      label: string;
      href: string;
      external?: boolean | null;
    };
    /**
     * Teaser VERBATIM, no proyección: no se actualiza solo si cambia el caso (§F2-2 · TEASER).
     */
    posts?:
      | {
          client: string;
          sector: string;
          sectorHref?: string | null;
          title: string;
          image: number | Media;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  articulos: {
    title: string;
    cta: {
      label: string;
      href: string;
      external?: boolean | null;
    };
    /**
     * Teaser VERBATIM, no proyección: no se actualiza solo si cambia la entrada (§F2-2 · TEASER).
     */
    posts?:
      | {
          title: string;
          /**
           * Fecha VERBATIM en la forma del teaser ("Mar 25, 2026"). El documento la escribe de otra forma ("25 marzo 2026") y las dos son verbatim: no se derivan la una de la otra.
           */
          date: string;
          image: number | Media;
          href: string;
          excerpt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  taxonomy: {
    label: string;
    href: string;
    external?: boolean | null;
  };
  footerStripImage?: (number | null) | Media;
  /**
   * Sólo «Publicado» sale en el sitio. Un borrador se ve en la preview con credencial.
   */
  estado: 'borrador' | 'publicado';
  /**
   * Si está en Borrador y esta hora pasa, el cron lo publica y reconstruye. Vacío = manual.
   */
  publicarEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "casos".
 */
export interface Caso {
  id: number;
  slug: string;
  /**
   * Defecto "casos-de-exito" — §2b · CMS-1 · D2 · 4 de 57
   */
  prefijo?: ('casos-de-exito' | 'case-studies') | null;
  seo: {
    title: string;
    description?: string | null;
    ogImage?: string | null;
  };
  titulo: string;
  imagenCabecera: number | Media;
  cliente: string;
  sectores?: (number | TaxonomiaSectore)[] | null;
  /**
   * HTML del corpus (CMS-0e · §3.1). Admite las 43 etiquetas censadas en 209/209. Prohibido `<script>` (§3.3 · T4). Rango medido: 275–69 784 caracteres.
   */
  necesidad: string;
  /**
   * HTML del corpus (CMS-0e · §3.1). Admite las 43 etiquetas censadas en 209/209. Prohibido `<script>` (§3.3 · T4). Rango medido: 275–69 784 caracteres.
   */
  solucion: string;
  /**
   * HTML del corpus (CMS-0e · §3.1). Admite las 43 etiquetas censadas en 209/209. Prohibido `<script>` (§3.3 · T4). Rango medido: 275–69 784 caracteres.
   */
  resultados: string;
  /**
   * HTML de LÍNEA (`CampoRicoEnLinea`): strong · b · i · br · sub · sup · a. Sin bloques ni `<p>` propio.
   */
  destacado?: string | null;
  galeria?:
    | {
        src: number | Media;
        alt?: string | null;
        width?: number | null;
        height?: number | null;
        id?: string | null;
      }[]
    | null;
  detalles: {
    usuario: string;
    ubicacion: string;
    anyo: string;
    /**
     * HTML del corpus (CMS-0e · §3.1). Admite las 43 etiquetas censadas en 209/209. Prohibido `<script>` (§3.3 · T4). Rango medido: 275–69 784 caracteres.
     */
    parametros?: string | null;
  };
  ubicacionMapa?: {
    lat?: number | null;
    lng?: number | null;
  };
  soluciones?: (number | Producto)[] | null;
  /**
   * Sólo «Publicado» sale en el sitio. Un borrador se ve en la preview con credencial.
   */
  estado: 'borrador' | 'publicado';
  /**
   * Si está en Borrador y esta hora pasa, el cron lo publica y reconstruye. Vacío = manual.
   */
  publicarEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomia-sectores".
 */
export interface TaxonomiaSectore {
  id: number;
  slug: string;
  nombre: string;
  pagina?:
    | ({
        relationTo: 'sectores';
        value: number | Sectore;
      } | null)
    | ({
        relationTo: 'monograficos';
        value: number | Monografico;
      } | null);
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  slug: string;
  seo: {
    title: string;
  };
  titulo: string;
  /**
   * HTML del corpus (CMS-0e · §3.1). Admite las 43 etiquetas censadas en 209/209. Prohibido `<script>` (§3.3 · T4). Rango medido: 275–69 784 caracteres.
   */
  cuerpo: string;
  /**
   * Sólo «Publicado» sale en el sitio. Un borrador se ve en la preview con credencial.
   */
  estado: 'borrador' | 'publicado';
  /**
   * Si está en Borrador y esta hora pasa, el cron lo publica y reconstruye. Vacío = manual.
   */
  publicarEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entradas-blog".
 */
export interface EntradasBlog {
  id: number;
  slug: string;
  seo: {
    title: string;
    description?: string | null;
    ogImage?: string | null;
  };
  titulo: string;
  fechaPublicacion: string;
  fechaActualizacion?: string | null;
  imagenDestacada?: {
    src?: (number | null) | Media;
    srcset?: string | null;
    sizes?: string | null;
    width?: string | null;
    height?: string | null;
    alt?: string | null;
  };
  extracto?: string | null;
  categorias: (number | Categoria)[];
  etiquetas?: (number | Etiqueta)[] | null;
  recurso?: (number | null) | CategoriasRecurso;
  /**
   * HTML del corpus (CMS-0e · §3.1). Admite las 43 etiquetas censadas en 209/209. Prohibido `<script>` (§3.3 · T4). Rango medido: 275–69 784 caracteres.
   */
  cuerpo: string;
  relacionados?: boolean | null;
  /**
   * Sólo «Publicado» sale en el sitio. Un borrador se ve en la preview con credencial.
   */
  estado: 'borrador' | 'publicado';
  /**
   * Si está en Borrador y esta hora pasa, el cron lo publica y reconstruye. Vacío = manual.
   */
  publicarEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SIN CENSAR (LH-SP8) — solo el mínimo de `TerminoA`. Censar antes de F2-2.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  nombre: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etiquetas".
 */
export interface Etiqueta {
  id: number;
  nombre: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-recursos".
 */
export interface CategoriasRecurso {
  id: number;
  nombre: string;
  slug: string;
  padre?: (number | null) | CategoriasRecurso;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terminos-kunakpedia".
 */
export interface TerminosKunakpedia {
  id: number;
  slug: string;
  seo: {
    title: string;
    description?: string | null;
    ogImage?: string | null;
  };
  titulo: string;
  /**
   * Defecto null — §2c.1 · 3 términos de 37
   */
  tituloMiga?: string | null;
  /**
   * HTML del corpus (CMS-0e · §3.1). Admite las 43 etiquetas censadas en 209/209. Prohibido `<script>` (§3.3 · T4). Rango medido: 275–69 784 caracteres.
   */
  cuerpo: string;
  /**
   * Sólo «Publicado» sale en el sitio. Un borrador se ve en la preview con credencial.
   */
  estado: 'borrador' | 'publicado';
  /**
   * Si está en Borrador y esta hora pasa, el cron lo publica y reconstruye. Vacío = manual.
   */
  publicarEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos-cientificos".
 */
export interface DocumentosCientifico {
  id: number;
  slug: string;
  /**
   * Defecto "documentos-cientificos" — §2.4 · 1 de 23
   */
  prefijo?: ('documentos-cientificos' | 'estudios-cientificos') | null;
  categoria: number | CategoriasCientifica;
  seo: {
    title: string;
    description?: string | null;
    ogImage?: string | null;
  };
  titulo: string;
  autores: string;
  anyo: string;
  portada: {
    src: number | Media;
    srcset?: string | null;
    sizes?: string | null;
    width?: string | null;
    height?: string | null;
    alt?: string | null;
  };
  descarga: {
    href: string;
    label: string;
  };
  /**
   * HTML del corpus (CMS-0e · §3.1). Admite las 43 etiquetas censadas en 209/209. Prohibido `<script>` (§3.3 · T4). Rango medido: 275–69 784 caracteres.
   */
  cuerpo: string;
  /**
   * Sólo «Publicado» sale en el sitio. Un borrador se ve en la preview con credencial.
   */
  estado: 'borrador' | 'publicado';
  /**
   * Si está en Borrador y esta hora pasa, el cron lo publica y reconstruye. Vacío = manual.
   */
  publicarEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-cientificas".
 */
export interface CategoriasCientifica {
  id: number;
  nombre: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articulos-kb".
 */
export interface ArticulosKb {
  id: number;
  slug: string;
  seo: {
    title: string;
    description?: string | null;
    ogImage?: string | null;
  };
  titulo: string;
  cuerpo?:
    | (
        | {
            texto: string;
            /**
             * Defecto 3 — §1.5 · MonoNivel 2|3|4 — el titular lo lee con `?? 3` en MonoCuerpo.tsx
             */
            nivel?: number | null;
            ritmo?: {
              mt?: number | null;
              mb?: number | null;
              pt?: number | null;
              pb?: number | null;
              pr?: number | null;
              mbAlterno?: boolean | null;
            };
            /**
             * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
             */
            anchoPct?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'titular';
          }
        | {
            texto: string;
            /**
             * Defecto 2 — §1.5 · MonoNivel 2|3|4 — el claim lo lee con `?? 2` en MonoCuerpo.tsx
             */
            nivel?: number | null;
            ritmo?: {
              mt?: number | null;
              mb?: number | null;
              pt?: number | null;
              pb?: number | null;
              pr?: number | null;
              mbAlterno?: boolean | null;
            };
            /**
             * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
             */
            anchoPct?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'claim';
          }
        | {
            bloques: (
              | {
                  p: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  pb?: number | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'p';
                }
              | {
                  ul?:
                    | {
                        texto: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        };
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'ul';
                }
              | {
                  claim?: string | null;
                  /**
                   * Defecto 2 — §1.5 · MonoNivel 2|3|4 — el claim lo lee con `?? 2` en MonoCuerpo.tsx
                   */
                  nivel?: number | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'claim';
                }
              | {
                  titular: string;
                  /**
                   * Defecto 3 — §1.5 · MonoNivel 2|3|4 — el titular lo lee con `?? 3` en MonoCuerpo.tsx
                   */
                  nivel?: number | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'titular';
                }
            )[];
            /**
             * Defecto 30.6 — §1.5 · 30.6·36·45 por módulo
             */
            lh?: number | null;
            ritmo?: {
              mt?: number | null;
              mb?: number | null;
              pt?: number | null;
              pb?: number | null;
              pr?: number | null;
              mbAlterno?: boolean | null;
            };
            /**
             * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
             */
            anchoPct?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'texto';
          }
        | {
            src: number | Media;
            alt?: string | null;
            ritmo?: {
              mt?: number | null;
              mb?: number | null;
              pt?: number | null;
              pb?: number | null;
              pr?: number | null;
              mbAlterno?: boolean | null;
            };
            /**
             * Defecto 100 — §1.5 · §6c.1 · clase-rango-{1440,390}.json
             */
            anchoPct?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagen';
          }
        | {
            label: string;
            href: string;
            external?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'boton';
          }
      )[]
    | null;
  /**
   * Sólo «Publicado» sale en el sitio. Un borrador se ve en la preview con credencial.
   */
  estado: 'borrador' | 'publicado';
  /**
   * Si está en Borrador y esta hora pasa, el cron lo publica y reconstruye. Vacío = manual.
   */
  publicarEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro del plano de /es/ — un segmento. Lo escriben los hooks de las colecciones de contenido; no se edita a mano. La unicidad ENTRE familias vive aquí (§4).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slugs".
 */
export interface Slug {
  id: number;
  slug: string;
  familia: string;
  documento?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nombre?: string | null;
  /**
   * Editor: edita y publica contenido. Admin: además gestiona usuarios y ve el registro del sistema. Sólo un admin puede cambiar este campo.
   */
  rol: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'sectores';
        value: number | Sectore;
      } | null)
    | ({
        relationTo: 'monograficos';
        value: number | Monografico;
      } | null)
    | ({
        relationTo: 'productos';
        value: number | Producto;
      } | null)
    | ({
        relationTo: 'casos';
        value: number | Caso;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'taxonomia-sectores';
        value: number | TaxonomiaSectore;
      } | null)
    | ({
        relationTo: 'entradas-blog';
        value: number | EntradasBlog;
      } | null)
    | ({
        relationTo: 'terminos-kunakpedia';
        value: number | TerminosKunakpedia;
      } | null)
    | ({
        relationTo: 'documentos-cientificos';
        value: number | DocumentosCientifico;
      } | null)
    | ({
        relationTo: 'articulos-kb';
        value: number | ArticulosKb;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'etiquetas';
        value: number | Etiqueta;
      } | null)
    | ({
        relationTo: 'categorias-recursos';
        value: number | CategoriasRecurso;
      } | null)
    | ({
        relationTo: 'categorias-cientificas';
        value: number | CategoriasCientifica;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'slugs';
        value: number | Slug;
      } | null)
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectores_select".
 */
export interface SectoresSelect<T extends boolean = true> {
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        canonical?: T;
      };
  breadcrumb?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  header?:
    | T
    | {
        kicker?: T;
        title?: T;
        image?: T;
      };
  hero?:
    | T
    | {
        image?:
          | T
          | {
              src?: T;
              alt?: T;
            };
        ctas?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
              id?: T;
            };
        heading?: T;
        headingColor?: T;
        paragraphs?:
          | T
          | {
              texto?: T;
              id?: T;
            };
      };
  body?:
    | T
    | {
        ctaDescarga?:
          | T
          | {
              title?: T;
              body?:
                | T
                | {
                    texto?: T;
                    id?: T;
                  };
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                  };
              image?: T;
              variante?: T;
              flujo?: T;
              anchoPct?: T;
              id?: T;
              blockName?: T;
            };
        beneficiosAplicaciones?:
          | T
          | {
              left?:
                | T
                | {
                    title?: T;
                    items?:
                      | T
                      | {
                          texto?: T;
                          id?: T;
                        };
                  };
              right?:
                | T
                | {
                    title?: T;
                    items?:
                      | T
                      | {
                          texto?: T;
                          id?: T;
                        };
                  };
              flujo?: T;
              anchoPct?: T;
              id?: T;
              blockName?: T;
            };
        claimConFoto?:
          | T
          | {
              claim?: T;
              image?:
                | T
                | {
                    src?: T;
                    alt?: T;
                  };
              flujo?: T;
              anchoPct?: T;
              id?: T;
              blockName?: T;
            };
        listaSimple2Col?:
          | T
          | {
              intro?: T;
              left?:
                | T
                | {
                    texto?: T;
                    id?: T;
                  };
              right?:
                | T
                | {
                    texto?: T;
                    id?: T;
                  };
              flujo?: T;
              anchoPct?: T;
              id?: T;
              blockName?: T;
            };
        mapaProyectos?:
          | T
          | {
              title?: T;
              intro?: T;
              pins?:
                | T
                | {
                    title?: T;
                    lat?: T;
                    lng?: T;
                    id?: T;
                  };
              flujo?: T;
              anchoPct?: T;
              id?: T;
              blockName?: T;
            };
      };
  ctaSlides?:
    | T
    | {
        heading?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
            };
        image?: T;
        id?: T;
      };
  soluciones?: T;
  proyectos?:
    | T
    | {
        title?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
            };
        posts?:
          | T
          | {
              client?: T;
              sector?: T;
              sectorHref?: T;
              title?: T;
              image?: T;
              href?: T;
              id?: T;
            };
      };
  articulos?:
    | T
    | {
        title?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
            };
        posts?:
          | T
          | {
              title?: T;
              date?: T;
              image?: T;
              href?: T;
              excerpt?: T;
              id?: T;
            };
      };
  taxonomy?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
      };
  footerStripImage?: T;
  estado?: T;
  publicarEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monograficos_select".
 */
export interface MonograficosSelect<T extends boolean = true> {
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        canonical?: T;
      };
  breadcrumb?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  header?:
    | T
    | {
        kicker?: T;
        title?: T;
        image?: T;
      };
  hero?:
    | T
    | {
        image?:
          | T
          | {
              src?: T;
              alt?: T;
            };
        ctas?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
              id?: T;
            };
        modulos?:
          | T
          | {
              heading?: T;
              headingColor?: T;
              paragraphs?:
                | T
                | {
                    texto?: T;
                    id?: T;
                  };
              mb?: T;
              id?: T;
            };
        pb?: T;
      };
  cuerpo?:
    | T
    | {
        mt?: T;
        pt?: T;
        pb?: T;
        filas?:
          | T
          | {
              mt?: T;
              pt?: T;
              pb?: T;
              columnas?:
                | T
                | {
                    ancho?: T;
                    punteado?: T;
                    mbMovil?: T;
                    modulos?:
                      | T
                      | {
                          titular?:
                            | T
                            | {
                                texto?: T;
                                nivel?: T;
                                ritmo?:
                                  | T
                                  | {
                                      mt?: T;
                                      mb?: T;
                                      pt?: T;
                                      pb?: T;
                                      pr?: T;
                                      mbAlterno?: T;
                                    };
                                anchoPct?: T;
                                id?: T;
                                blockName?: T;
                              };
                          claim?:
                            | T
                            | {
                                texto?: T;
                                nivel?: T;
                                ritmo?:
                                  | T
                                  | {
                                      mt?: T;
                                      mb?: T;
                                      pt?: T;
                                      pb?: T;
                                      pr?: T;
                                      mbAlterno?: T;
                                    };
                                anchoPct?: T;
                                id?: T;
                                blockName?: T;
                              };
                          texto?:
                            | T
                            | {
                                bloques?:
                                  | T
                                  | {
                                      p?:
                                        | T
                                        | {
                                            p?: T;
                                            pb?: T;
                                            id?: T;
                                            blockName?: T;
                                          };
                                      ul?:
                                        | T
                                        | {
                                            ul?:
                                              | T
                                              | {
                                                  texto?: T;
                                                  id?: T;
                                                };
                                            id?: T;
                                            blockName?: T;
                                          };
                                      claim?:
                                        | T
                                        | {
                                            claim?: T;
                                            nivel?: T;
                                            id?: T;
                                            blockName?: T;
                                          };
                                      titular?:
                                        | T
                                        | {
                                            titular?: T;
                                            nivel?: T;
                                            id?: T;
                                            blockName?: T;
                                          };
                                    };
                                lh?: T;
                                ritmo?:
                                  | T
                                  | {
                                      mt?: T;
                                      mb?: T;
                                      pt?: T;
                                      pb?: T;
                                      pr?: T;
                                      mbAlterno?: T;
                                    };
                                anchoPct?: T;
                                id?: T;
                                blockName?: T;
                              };
                          imagen?:
                            | T
                            | {
                                src?: T;
                                alt?: T;
                                ritmo?:
                                  | T
                                  | {
                                      mt?: T;
                                      mb?: T;
                                      pt?: T;
                                      pb?: T;
                                      pr?: T;
                                      mbAlterno?: T;
                                    };
                                anchoPct?: T;
                                id?: T;
                                blockName?: T;
                              };
                          boton?:
                            | T
                            | {
                                label?: T;
                                href?: T;
                                external?: T;
                                id?: T;
                                blockName?: T;
                              };
                          serie?:
                            | T
                            | {
                                items?:
                                  | T
                                  | {
                                      titulo?: T;
                                      texto?: T;
                                      id?: T;
                                    };
                                ritmo?:
                                  | T
                                  | {
                                      mt?: T;
                                      mb?: T;
                                      pt?: T;
                                      pb?: T;
                                      pr?: T;
                                      mbAlterno?: T;
                                    };
                                anchoPct?: T;
                                id?: T;
                                blockName?: T;
                              };
                          tabla?:
                            | T
                            | {
                                cabeceras?:
                                  | T
                                  | {
                                      texto?: T;
                                      id?: T;
                                    };
                                filas?:
                                  | T
                                  | {
                                      celdas?:
                                        | T
                                        | {
                                            texto?: T;
                                            fuerte?: T;
                                            resto?: T;
                                            id?: T;
                                          };
                                      id?: T;
                                    };
                                ritmo?:
                                  | T
                                  | {
                                      mt?: T;
                                      mb?: T;
                                      pt?: T;
                                      pb?: T;
                                      pr?: T;
                                      mbAlterno?: T;
                                    };
                                anchoPct?: T;
                                id?: T;
                                blockName?: T;
                              };
                          ctaDescarga?:
                            | T
                            | {
                                title?: T;
                                body?:
                                  | T
                                  | {
                                      texto?: T;
                                      id?: T;
                                    };
                                cta?:
                                  | T
                                  | {
                                      label?: T;
                                      href?: T;
                                      external?: T;
                                    };
                                image?: T;
                                ritmo?:
                                  | T
                                  | {
                                      mt?: T;
                                      mb?: T;
                                      pt?: T;
                                      pb?: T;
                                      pr?: T;
                                      mbAlterno?: T;
                                    };
                                anchoPct?: T;
                                id?: T;
                                blockName?: T;
                              };
                          mapaProyectos?:
                            | T
                            | {
                                pins?:
                                  | T
                                  | {
                                      title?: T;
                                      lat?: T;
                                      lng?: T;
                                      id?: T;
                                    };
                                ritmo?:
                                  | T
                                  | {
                                      mt?: T;
                                      mb?: T;
                                      pt?: T;
                                      pb?: T;
                                      pr?: T;
                                      mbAlterno?: T;
                                    };
                                anchoPct?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  ctaSlides?:
    | T
    | {
        heading?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
            };
        image?: T;
        id?: T;
      };
  soluciones?: T;
  proyectos?:
    | T
    | {
        title?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
            };
        posts?:
          | T
          | {
              client?: T;
              sector?: T;
              sectorHref?: T;
              title?: T;
              image?: T;
              href?: T;
              id?: T;
            };
      };
  articulos?:
    | T
    | {
        title?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
            };
        posts?:
          | T
          | {
              title?: T;
              date?: T;
              image?: T;
              href?: T;
              excerpt?: T;
              id?: T;
            };
      };
  taxonomy?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
      };
  footerStripImage?: T;
  estado?: T;
  publicarEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productos_select".
 */
export interface ProductosSelect<T extends boolean = true> {
  slug?: T;
  titulo?: T;
  tipo?: T;
  padre?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  tagline?: T;
  description?: T;
  highlight?: T;
  bulletsTitulo?: T;
  bullets?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  image?: T;
  cuerpo?:
    | T
    | {
        titular?:
          | T
          | {
              texto?: T;
              nivel?: T;
              ritmo?:
                | T
                | {
                    mt?: T;
                    mb?: T;
                    pt?: T;
                    pb?: T;
                    pr?: T;
                    mbAlterno?: T;
                  };
              anchoPct?: T;
              id?: T;
              blockName?: T;
            };
        claim?:
          | T
          | {
              texto?: T;
              nivel?: T;
              ritmo?:
                | T
                | {
                    mt?: T;
                    mb?: T;
                    pt?: T;
                    pb?: T;
                    pr?: T;
                    mbAlterno?: T;
                  };
              anchoPct?: T;
              id?: T;
              blockName?: T;
            };
        texto?:
          | T
          | {
              bloques?:
                | T
                | {
                    p?:
                      | T
                      | {
                          p?: T;
                          pb?: T;
                          id?: T;
                          blockName?: T;
                        };
                    ul?:
                      | T
                      | {
                          ul?:
                            | T
                            | {
                                texto?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    claim?:
                      | T
                      | {
                          claim?: T;
                          nivel?: T;
                          id?: T;
                          blockName?: T;
                        };
                    titular?:
                      | T
                      | {
                          titular?: T;
                          nivel?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              lh?: T;
              ritmo?:
                | T
                | {
                    mt?: T;
                    mb?: T;
                    pt?: T;
                    pb?: T;
                    pr?: T;
                    mbAlterno?: T;
                  };
              anchoPct?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              src?: T;
              alt?: T;
              ritmo?:
                | T
                | {
                    mt?: T;
                    mb?: T;
                    pt?: T;
                    pb?: T;
                    pr?: T;
                    mbAlterno?: T;
                  };
              anchoPct?: T;
              id?: T;
              blockName?: T;
            };
        boton?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
              id?: T;
              blockName?: T;
            };
        toggle?:
          | T
          | {
              titulo?: T;
              contenido?: T;
              abiertoPorDefecto?: T;
              id?: T;
              blockName?: T;
            };
        blurb?:
          | T
          | {
              titulo?: T;
              texto?: T;
              icono?: T;
              id?: T;
              blockName?: T;
            };
        slider?:
          | T
          | {
              diapositivas?:
                | T
                | {
                    heading?: T;
                    texto?: T;
                    image?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          external?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              imagenes?:
                | T
                | {
                    src?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              archivo?: T;
              url?: T;
              poster?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?:
                | T
                | {
                    texto?: T;
                    id?: T;
                  };
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                  };
              image?: T;
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              cabeceras?:
                | T
                | {
                    texto?: T;
                    id?: T;
                  };
              filas?:
                | T
                | {
                    celdas?:
                      | T
                      | {
                          texto?: T;
                          fuerte?: T;
                          resto?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  estado?: T;
  publicarEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "casos_select".
 */
export interface CasosSelect<T extends boolean = true> {
  slug?: T;
  prefijo?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  titulo?: T;
  imagenCabecera?: T;
  cliente?: T;
  sectores?: T;
  necesidad?: T;
  solucion?: T;
  resultados?: T;
  destacado?: T;
  galeria?:
    | T
    | {
        src?: T;
        alt?: T;
        width?: T;
        height?: T;
        id?: T;
      };
  detalles?:
    | T
    | {
        usuario?: T;
        ubicacion?: T;
        anyo?: T;
        parametros?: T;
      };
  ubicacionMapa?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  soluciones?: T;
  estado?: T;
  publicarEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
      };
  titulo?: T;
  cuerpo?: T;
  estado?: T;
  publicarEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomia-sectores_select".
 */
export interface TaxonomiaSectoresSelect<T extends boolean = true> {
  slug?: T;
  nombre?: T;
  pagina?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entradas-blog_select".
 */
export interface EntradasBlogSelect<T extends boolean = true> {
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  titulo?: T;
  fechaPublicacion?: T;
  fechaActualizacion?: T;
  imagenDestacada?:
    | T
    | {
        src?: T;
        srcset?: T;
        sizes?: T;
        width?: T;
        height?: T;
        alt?: T;
      };
  extracto?: T;
  categorias?: T;
  etiquetas?: T;
  recurso?: T;
  cuerpo?: T;
  relacionados?: T;
  estado?: T;
  publicarEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terminos-kunakpedia_select".
 */
export interface TerminosKunakpediaSelect<T extends boolean = true> {
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  titulo?: T;
  tituloMiga?: T;
  cuerpo?: T;
  estado?: T;
  publicarEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos-cientificos_select".
 */
export interface DocumentosCientificosSelect<T extends boolean = true> {
  slug?: T;
  prefijo?: T;
  categoria?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  titulo?: T;
  autores?: T;
  anyo?: T;
  portada?:
    | T
    | {
        src?: T;
        srcset?: T;
        sizes?: T;
        width?: T;
        height?: T;
        alt?: T;
      };
  descarga?:
    | T
    | {
        href?: T;
        label?: T;
      };
  cuerpo?: T;
  estado?: T;
  publicarEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articulos-kb_select".
 */
export interface ArticulosKbSelect<T extends boolean = true> {
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  titulo?: T;
  cuerpo?:
    | T
    | {
        titular?:
          | T
          | {
              texto?: T;
              nivel?: T;
              ritmo?:
                | T
                | {
                    mt?: T;
                    mb?: T;
                    pt?: T;
                    pb?: T;
                    pr?: T;
                    mbAlterno?: T;
                  };
              anchoPct?: T;
              id?: T;
              blockName?: T;
            };
        claim?:
          | T
          | {
              texto?: T;
              nivel?: T;
              ritmo?:
                | T
                | {
                    mt?: T;
                    mb?: T;
                    pt?: T;
                    pb?: T;
                    pr?: T;
                    mbAlterno?: T;
                  };
              anchoPct?: T;
              id?: T;
              blockName?: T;
            };
        texto?:
          | T
          | {
              bloques?:
                | T
                | {
                    p?:
                      | T
                      | {
                          p?: T;
                          pb?: T;
                          id?: T;
                          blockName?: T;
                        };
                    ul?:
                      | T
                      | {
                          ul?:
                            | T
                            | {
                                texto?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    claim?:
                      | T
                      | {
                          claim?: T;
                          nivel?: T;
                          id?: T;
                          blockName?: T;
                        };
                    titular?:
                      | T
                      | {
                          titular?: T;
                          nivel?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              lh?: T;
              ritmo?:
                | T
                | {
                    mt?: T;
                    mb?: T;
                    pt?: T;
                    pb?: T;
                    pr?: T;
                    mbAlterno?: T;
                  };
              anchoPct?: T;
              id?: T;
              blockName?: T;
            };
        imagen?:
          | T
          | {
              src?: T;
              alt?: T;
              ritmo?:
                | T
                | {
                    mt?: T;
                    mb?: T;
                    pt?: T;
                    pb?: T;
                    pr?: T;
                    mbAlterno?: T;
                  };
              anchoPct?: T;
              id?: T;
              blockName?: T;
            };
        boton?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
              id?: T;
              blockName?: T;
            };
      };
  estado?: T;
  publicarEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etiquetas_select".
 */
export interface EtiquetasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-recursos_select".
 */
export interface CategoriasRecursosSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  padre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias-cientificas_select".
 */
export interface CategoriasCientificasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  rutaOrigen?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        w300?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        sm?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w768?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        md?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        lg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cardWide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slugs_select".
 */
export interface SlugsSelect<T extends boolean = true> {
  slug?: T;
  familia?: T;
  documento?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}